package GUI;

import DTO.Message_11DTO;
import DTO.UserDTO;
import Func.Hyrid_Encryption;
import Func.fileFunc;
import Network.Config;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.net.Socket;
import java.security.NoSuchAlgorithmException;
import java.security.PublicKey;
import java.util.Base64;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.KeyGenerator;
import javax.crypto.SecretKey;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import javax.swing.filechooser.FileNameExtensionFilter;

public class Chat_Room_11 extends javax.swing.JFrame {

    UserDTO user;
    UserDTO userReceive;
    Socket socket;
    String PUBLIC_KEY_SERVER = "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCbPndbAp25koChNaXO9XfZHLBEVKWedG5c2Inio657AePBaYzYISc2ucXwHDzn+xJsFbthGzyt+CYsnVdrtwpVB3Pv7TpWnj2W2l0yG5vrOjsUERVBaC+6Mk1+RNXRimqxCJDtJTtXeB9/bZGXBe4WcPXUhwIB563JPyAGTyeVnwIDAQAB";
    String randomKey;
    PublicKey pKeyServer;
    BufferedReader input;
    BufferedWriter output;
    IOThread iothread;

    public Chat_Room_11() {
        initComponents();
    }

    public Chat_Room_11(UserDTO user, UserDTO userReceive) {
        this.user = user;
        this.userReceive = userReceive;
        initComponents();
        initDisplay();
        initSocket();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        chat_message = new javax.swing.JScrollPane();
        input_chat = new javax.swing.JTextField();
        name_group = new javax.swing.JLabel();
        sendFileBtn = new javax.swing.JLabel();
        sendMessBtn = new javax.swing.JLabel();
        sendStickerBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(chat_message, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 690, 500));

        input_chat.setBackground(new java.awt.Color(254, 254, 254));
        input_chat.setFont(new java.awt.Font("Arimo", 0, 24)); // NOI18N
        jPanel1.add(input_chat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 550, 48));

        name_group.setFont(new java.awt.Font("Arimo", 1, 24)); // NOI18N
        name_group.setForeground(new java.awt.Color(25, 113, 216));
        name_group.setText("jLabel1");
        jPanel1.add(name_group, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 830, -1));

        sendFileBtn.setFont(new java.awt.Font("Arimo", 1, 18)); // NOI18N
        sendFileBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sendFileBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-file-48.png"))); // NOI18N
        sendFileBtn.setText("FIle");
        sendFileBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 160, 253), 2));
        sendFileBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendFileBtnMouseClicked(evt);
            }
        });
        jPanel1.add(sendFileBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 580, 120, 50));

        sendMessBtn.setFont(new java.awt.Font("Arimo", 1, 18)); // NOI18N
        sendMessBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sendMessBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-send-32.png"))); // NOI18N
        sendMessBtn.setText("Gửi");
        sendMessBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 160, 253), 2));
        sendMessBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendMessBtnMouseClicked(evt);
            }
        });
        jPanel1.add(sendMessBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 580, 90, 50));

        sendStickerBtn.setFont(new java.awt.Font("Arimo", 1, 18)); // NOI18N
        sendStickerBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sendStickerBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-sticker-48.png"))); // NOI18N
        sendStickerBtn.setText("Sticker");
        sendStickerBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 160, 253), 2));
        sendStickerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendStickerBtnMouseClicked(evt);
            }
        });
        jPanel1.add(sendStickerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 520, 120, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendStickerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendStickerBtnMouseClicked
        // TODO add your handling code here:
        new Sticker_Select_11(user, userReceive, chat_message).setVisible(true);
    }//GEN-LAST:event_sendStickerBtnMouseClicked

    private void sendFileBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendFileBtnMouseClicked
        // TODO add your handling code here:
        JFileChooser filechoose = new JFileChooser();
        FileNameExtensionFilter extension = new FileNameExtensionFilter("Chon file", "txt");
        filechoose.setFileFilter(extension);
        String content = "";
        File file = null;
        int choose = filechoose.showDialog(this, "Chon file");

        if (choose == JFileChooser.APPROVE_OPTION) {
            file = filechoose.getSelectedFile();
            if (file.length() >= 1000000) {
                JOptionPane.showMessageDialog(null, "Kích thước file phải nhỏ hơn 1MB");
                return;
            }
            content = file.getName();

            //Them vao chat
            Container container = new Container();
            for (Component c : chat_message.getViewport().getComponents()) {
                if (c instanceof Container) {
                    container = (Container) c;
                    break;
                }
            }

            container.add(new Right_Message_File(user.getName(), content, "", "", "Đang gửi"));

            container.setLayout(new GridLayout(container.getComponentCount(), 1));
            chat_message.getViewport().setView(container);
            input_chat.setText("");
            JScrollBar scrollBar = chat_message.getVerticalScrollBar();
            scrollBar.setValue(scrollBar.getMaximum());
            new Thread(new addNewFile(socket, randomKey, user, userReceive, pKeyServer, file)).start();
        }
    }//GEN-LAST:event_sendFileBtnMouseClicked

    private void sendMessBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendMessBtnMouseClicked
        // TODO add your handling code here:
        String content = input_chat.getText();
        if (content.compareTo("") == 0 || content.replaceAll(" ", "").compareTo("") == 0) {
            JOptionPane.showMessageDialog(null, "Nội dụng tin nhắn không được rỗng ");
            return;
        }

        //Them vao chat
        Container container = new Container();
        for (Component c : chat_message.getViewport().getComponents()) {
            if (c instanceof Container) {
                container = (Container) c;
                break;
            }
        }

        container.add(new Right_Message(user.getName(), content, "", "", "Đang gửi"));

        container.setLayout(new GridLayout(container.getComponentCount(), 1));
        chat_message.getViewport().setView(container);
        input_chat.setText("");
        JScrollBar scrollBar = chat_message.getVerticalScrollBar();
        scrollBar.setValue(scrollBar.getMaximum());

        PublicKey pKey = Hyrid_Encryption.getPublicKeyRSA(PUBLIC_KEY_SERVER);

        new Thread(new addNewMessage(socket, randomKey, pKeyServer, user, userReceive, content)).start();
    }//GEN-LAST:event_sendMessBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chat_Room_11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chat_Room_11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chat_Room_11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chat_Room_11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chat_Room_11().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane chat_message;
    private javax.swing.JTextField input_chat;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel name_group;
    private javax.swing.JLabel sendFileBtn;
    private javax.swing.JLabel sendMessBtn;
    private javax.swing.JLabel sendStickerBtn;
    // End of variables declaration//GEN-END:variables

    private void initDisplay() {
        name_group.setText(userReceive.getName());
    }

    private void initSocket() {
        int i = 0;
        while (i < 3) {
            try {
                this.socket = new Socket(Config.HOST, Config.PORT);
                input = new BufferedReader(new InputStreamReader(socket.getInputStream()));
                output = new BufferedWriter(new OutputStreamWriter(socket.getOutputStream()));
                //Tao random key
                KeyGenerator keyGen = KeyGenerator.getInstance("AES");
                keyGen.init(256); // for example
                SecretKey secretKey = keyGen.generateKey();
                randomKey = Base64.getEncoder().encodeToString(secretKey.getEncoded());
                pKeyServer = Hyrid_Encryption.getPublicKeyRSA(PUBLIC_KEY_SERVER);

                break;

            } catch (Exception ex) {
                try {
                    int choose = JOptionPane.showConfirmDialog(null, "Không thể kết nối đến Server đang thử kết nối lần " + (i + 1), "Cảnh báo", JOptionPane.YES_OPTION);
                    i++;
                    Thread.sleep(2500);

                } catch (InterruptedException ex1) {
                    JOptionPane.showMessageDialog(null, "Lỗi hệ thống, hệ thống sẽ thoát");
                    System.exit(0);
                }
            }

        }
        if (i >= 3) {
            JOptionPane.showMessageDialog(null, "Không thể kết nối đến server");
            System.exit(0);
        }

        iothread = new IOThread(input, output, randomKey, pKeyServer, chat_message, this, user, userReceive);
        new Thread(iothread).start();

        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent event) {
                iothread.Terminal();
                dispose();
            }
        });

        ActionListener ac = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                String content = input_chat.getText();
                if (content.compareTo("") == 0 || content.replaceAll(" ", "").compareTo("") == 0) {
                    JOptionPane.showMessageDialog(null, "Nội dụng tin nhắn không được rỗng ");
                    return;
                }

                //Them vao chat
                Container container = new Container();
                for (Component c : chat_message.getViewport().getComponents()) {
                    if (c instanceof Container) {
                        container = (Container) c;
                        break;
                    }
                }

                container.add(new Right_Message(user.getName(), content, "", "", "Đang gửi"));

                container.setLayout(new GridLayout(container.getComponentCount(), 1));
                chat_message.getViewport().setView(container);
                input_chat.setText("");
                JScrollBar scrollBar = chat_message.getVerticalScrollBar();
                scrollBar.setValue(scrollBar.getMaximum());

                new Thread(new Chat_Room_11.addNewMessage(socket, randomKey, pKeyServer, user, userReceive, content)).start();
            }
        };

        input_chat.addActionListener(ac);
    }

    private class IOThread implements Runnable {

        BufferedReader input;
        BufferedWriter output;
        String randomKey;
        PublicKey pKeyServer;
        JScrollPane chatmess;
        JFrame jrame;
        UserDTO user;
        UserDTO userReceive;
        boolean isBreak = false;

        public IOThread(BufferedReader input, BufferedWriter output, String randomKey, PublicKey pKeyServer, JScrollPane chatmess, JFrame jrame, UserDTO user, UserDTO userReceive) {
            this.input = input;
            this.output = output;
            this.randomKey = randomKey;
            this.pKeyServer = pKeyServer;
            this.chatmess = chatmess;
            this.jrame = jrame;
            this.user = user;
            this.userReceive = userReceive;
        }

        public void Terminal() {
            this.isBreak = true;
        }

        @Override
        public void run() {

            new Thread(new loadMessage11(socket, randomKey, user, userReceive, pKeyServer)).start();
            new Thread(new viewAllMess(socket, randomKey, user, userReceive, pKeyServer)).start();
            try {
                String currentContentMessage = "";
                while (!isBreak) {
                    // Doc du lieu
                    String inputStr = input.readLine();

                    //Giai ma du lieu
                    inputStr = Hyrid_Encryption.decryptAES(inputStr, randomKey);
                    if (inputStr == null) {
                        break;
                    }
                    //ep kieu thanh hashmap
                    HashMap<String, String> maps = new Gson().fromJson(inputStr, new TypeToken<HashMap<String, String>>() {
                    }.getType());
                    System.out.println(maps);

                    switch (maps.get("command")) {
                        case "LOAD_MESSAGE_11": {
                            List<Message_11DTO> listMessage11 = new Gson().fromJson(maps.get("data"), new TypeToken<List<Message_11DTO>>() {
                            }.getType());

                            Container conn = new Container();
                            String strMessage = "";
                            for (Message_11DTO mess : listMessage11) {
                                JPanel p = null;

                                //Sticker
                                if (mess.isIsURL() && mess.getContent().contains(".gif")) {
                                    if (!mess.isIsOwner()) {
                                        p = new Left_Message_Sticker(mess.getNameUser(), mess.getContent(), mess.getTime(), mess.getViewer(), "Đã gửi");
                                    } else {
                                        p = new Right_Message_Sticker(mess.getNameUser(), mess.getContent(), mess.getTime(), mess.getViewer(), "Đã gửi");
                                    }
                                } //FIle
                                else if (mess.isIsURL()) {
                                    if (!mess.isIsOwner()) {
                                        p = new Left_Message_File(mess.getNameUser(), mess.getContent(), mess.getTime(), mess.getViewer(), "Đã gửi");
                                    } else {
                                        p = new Right_Message_File(mess.getNameUser(), mess.getContent(), mess.getTime(), mess.getViewer(), "Đã gửi");
                                    }
                                } //Message
                                else {
                                    if (!mess.isIsOwner()) {
                                        p = new Left_Message(mess.getNameUser(), mess.getContent(), mess.getTime(), mess.getViewer(), "Đã gửi");
                                    } else {
                                        p = new Right_Message(mess.getNameUser(), mess.getContent(), mess.getTime(), mess.getViewer(), "Đã gửi");
                                    }
                                }

                                if (p != null) {
                                    strMessage += p.toString();
                                    p.setVisible(true);
                                    p.setBackground(Color.WHITE);
                                    conn.add(p);

                                }
                            }
                            if (currentContentMessage.compareTo(strMessage) != 0) {
                                conn.setLayout(new GridLayout(listMessage11.size(), 1));
                                chat_message.getViewport().setView(conn);
                                chat_message.getViewport().setBackground(Color.WHITE);
                                conn.setBackground(Color.WHITE);
                                JScrollBar scrollBar = chat_message.getVerticalScrollBar();
                                scrollBar.setValue(scrollBar.getMaximum());
                                currentContentMessage = strMessage;

                                new Thread(new readAllMessage(socket, randomKey, user, userReceive, pKeyServer)).start();
                            }
                            break;
                        }
                    }
                }
                input.close();
                output.close();

            }catch (Exception ex) {
                System.out.println(ex.getMessage());
            }
        }
    }

    public class addNewMessage implements Runnable {

        Socket socket;
        String randomkey;
        PublicKey pKeyServer;
        UserDTO user;
        UserDTO userReceive;
        String content;

        public addNewMessage(Socket socket, String randomkey, PublicKey pKeyServer, UserDTO user, UserDTO userReceive, String content) {
            this.socket = socket;
            this.randomkey = randomkey;
            this.pKeyServer = pKeyServer;
            this.user = user;
            this.userReceive = userReceive;
            this.content = content;
        }

        @Override
        public void run() {
            try {
                BufferedWriter output = new BufferedWriter(new OutputStreamWriter(socket.getOutputStream()));

                HashMap<String, String> map = new HashMap<>();
                String[] str = {
                    String.valueOf(user.getId()),
                    String.valueOf(userReceive.getId()),
                    content
                };

                //KHỞI TẠO DATA
                map.put("command", "ADD_MESSAGE_11");
                map.put("data", new Gson().toJson(str));

                //CHUYỂN DATA THÀNH JSON VÀ MÃ HOÁ DỮ LIỆU
                String data = new Gson().toJson(map);
                data = Hyrid_Encryption.encryptAES(data, randomKey);
                //Ma hoa randomkey
                String encryptRandomKey = Hyrid_Encryption.encryptRSA(randomKey, pKeyServer);
                //Tao du lieu gui den server                     
                HashMap<String, String> sendServer = new HashMap<>();
                sendServer.put("key", encryptRandomKey);
                sendServer.put("value", data);
                String strSend = new Gson().toJson(sendServer);

                output.write(strSend);
                output.newLine();
                output.flush();

            } catch (Exception ex) {
                System.out.println(ex.getMessage());
            }
        }
    }

    private class readAllMessage implements Runnable {

        Socket socket;
        String randomKey;
        UserDTO user;
        UserDTO userReceive;
        PublicKey pKeyServer;

        public readAllMessage(Socket socket, String randomKey, UserDTO user, UserDTO userReceive, PublicKey pKeyServer) {
            this.socket = socket;
            this.randomKey = randomKey;
            this.user = user;
            this.userReceive = userReceive;
            this.pKeyServer = pKeyServer;
        }

        @Override
        public void run() {
            try {
                BufferedWriter output = new BufferedWriter(new OutputStreamWriter(socket.getOutputStream()));

                HashMap<String, String> maps = new HashMap<>();
                int[] str = {user.getId(), userReceive.getId()};
                //Khoi tao data        
                maps.put("command", "VIEW_ALL_MESSAGE_11");
                maps.put("data", new Gson().toJson(str));

                //Ma hoa du lieu
                String data = new Gson().toJson(maps);
                data = Hyrid_Encryption.encryptAES(data, randomKey);
                //Ma hoa randomkey
                String encryptRandomKey = Hyrid_Encryption.encryptRSA(randomKey, pKeyServer);
                //Tao du lieu gui den server                     
                HashMap<String, String> sendServer = new HashMap<>();
                sendServer.put("key", encryptRandomKey);
                sendServer.put("value", data);
                String strSend = new Gson().toJson(sendServer);

                output.write(strSend);
                output.newLine();
                output.flush();

            } catch (Exception ex) {
                System.out.println(ex.getMessage());
            }
        }

    }

    private class loadMessage11 implements Runnable {

        Socket socket;
        String randomKey;
        UserDTO user;
        UserDTO userReceive;
        PublicKey pKeyServer;

        public loadMessage11(Socket socket, String randomKey, UserDTO user, UserDTO userReceive, PublicKey pKeyServer) {
            this.socket = socket;
            this.randomKey = randomKey;
            this.user = user;
            this.userReceive = userReceive;
            this.pKeyServer = pKeyServer;
        }

        @Override
        public void run() {
            try {
                BufferedWriter output = new BufferedWriter(new OutputStreamWriter(socket.getOutputStream()));
                while (true) {
                    HashMap<String, String> maps = new HashMap<>();
                    int[] str = {user.getId(), userReceive.getId()};
                    //Khoi tao data          
                    maps.put("command", "LOAD_MESSAGE_11");
                    maps.put("data", new Gson().toJson(str));
                    //Ma hoa du lieu
                    String data = new Gson().toJson(maps);
                    data = Hyrid_Encryption.encryptAES(data, randomKey);
                    //Ma hoa randomkey
                    String encryptRandomKey = Hyrid_Encryption.encryptRSA(randomKey, pKeyServer);
                    //Tao du lieu gui den server                     
                    HashMap<String, String> sendServer = new HashMap<>();
                    sendServer.put("key", encryptRandomKey);
                    sendServer.put("value", data);
                    String strSend = new Gson().toJson(sendServer);

                    output.write(strSend);
                    output.newLine();
                    output.flush();
                    Thread.sleep(Config.DELAY_TIME);
                }

            } catch (Exception ex) {
                System.out.println(ex.getMessage());
            }
        }
    }

    private static class viewAllMess implements Runnable {

        Socket socket;
        String randomKey;
        UserDTO user;
        UserDTO userReceive;
        PublicKey pKeyServer;

        public viewAllMess(Socket socket, String randomKey, UserDTO user, UserDTO userReceive, PublicKey pKeyServer) {
            this.socket = socket;
            this.randomKey = randomKey;
            this.user = user;
            this.userReceive = userReceive;
            this.pKeyServer = pKeyServer;
        }

        @Override
        public void run() {
            try {
                BufferedWriter output = new BufferedWriter(new OutputStreamWriter(socket.getOutputStream()));
                while (true) {
                    HashMap<String, String> maps = new HashMap<>();
                    int[] str = {user.getId(), userReceive.getId()};
                    //Khoi tao data          
                    maps.put("command", "VIEW_MESSAGE_11");
                    maps.put("data", new Gson().toJson(str));
                    //Ma hoa du lieu
                    String data = new Gson().toJson(maps);
                    data = Hyrid_Encryption.encryptAES(data, randomKey);
                    //Ma hoa randomkey
                    String encryptRandomKey = Hyrid_Encryption.encryptRSA(randomKey, pKeyServer);
                    //Tao du lieu gui den server                     
                    HashMap<String, String> sendServer = new HashMap<>();
                    sendServer.put("key", encryptRandomKey);
                    sendServer.put("value", data);
                    String strSend = new Gson().toJson(sendServer);

                    output.write(strSend);
                    output.newLine();
                    output.flush();
                    Thread.sleep(Config.DELAY_TIME);
                }

            } catch (Exception ex) {
                System.out.println(ex.getMessage());
            }
        }
    }

    private static class addNewFile implements Runnable {

        Socket socket;
        String randomKey;
        UserDTO user;
        UserDTO userReceive;
        PublicKey pKeyServer;
        File file;

        public addNewFile(Socket socket, String randomKey, UserDTO user, UserDTO userReceive, PublicKey pKeyServer, File file) {
            this.socket = socket;
            this.randomKey = randomKey;
            this.user = user;
            this.userReceive = userReceive;
            this.pKeyServer = pKeyServer;
            this.file = file;
        }

        @Override
        public void run() {
            try {
                String fileUrl = file.getAbsolutePath();
                byte[] datafile = fileFunc.convertFileToByte(fileUrl);

                BufferedWriter output = new BufferedWriter(new OutputStreamWriter(socket.getOutputStream()));
                String[] str = {
                    String.valueOf(user.getId()),
                    String.valueOf(userReceive.getId()),
                    file.getName(),
                    new Gson().toJson(datafile)
                };
                HashMap<String, String> maps = new HashMap<>();

                //Khoi tao data          
                maps.put("command", "ADD_FILE_MESSAGE_11");
                maps.put("data", new Gson().toJson(str));
                //Ma hoa du lieu
                String data = new Gson().toJson(maps);
                data = Hyrid_Encryption.encryptAES(data, randomKey);
                //Ma hoa randomkey
                String encryptRandomKey = Hyrid_Encryption.encryptRSA(randomKey, pKeyServer);
                //Tao du lieu gui den server                     
                HashMap<String, String> sendServer = new HashMap<>();
                sendServer.put("key", encryptRandomKey);
                sendServer.put("value", data);
                String strSend = new Gson().toJson(sendServer);

                output.write(strSend);
                output.newLine();
                output.flush();
                Thread.sleep(Config.DELAY_TIME);
            } catch (Exception ex) {
                System.out.println(ex.getMessage());
            }
        }
    }
}
