/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DTO.Message;
import java.awt.Color;
import javax.swing.BorderFactory;

/**
 *
 * @author mthuan
 */
public class Right_Mesage extends javax.swing.JPanel {
    Message mess;
    /**
     * Creates new form Left_Mesage
     */
    public Right_Mesage(Message m,String viewUser) {
        this.mess = m;
        initComponents();
        user_name.setText(mess.getUsername());
        content.setText(mess.getBody());
        status_view.setText("Đã gửi");
        time_sent.setText(mess.getTime());
        background.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 0, Color.black));
        
        if(viewUser.compareTo("") == 0){
            status_view.setText("Đã gửi");
        }
        else{
            status_view.setText(viewUser + " đã xem");
        }
    }
    
    public Right_Mesage(String username,String contentBody){
        initComponents();
        user_name.setText(username);
        content.setText(contentBody);
        status_view.setText("Đang gửi");
        background.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 0, Color.black));
    }
    
    public String getContent(){
        return user_name.getText() + content.getText()+status_view.getText();
    }
    

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        user_name = new javax.swing.JLabel();
        status_view = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        content = new javax.swing.JTextArea();
        time_sent = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(254, 254, 254));
        background.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user_name.setFont(new java.awt.Font("Arimo", 0, 18)); // NOI18N
        user_name.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        user_name.setText("jLabel1");
        background.add(user_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 440, -1));

        status_view.setFont(new java.awt.Font("Arimo", 0, 18)); // NOI18N
        status_view.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        status_view.setText("jLabel1");
        background.add(status_view, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 440, -1));

        content.setColumns(20);
        content.setFont(new java.awt.Font("Arimo", 0, 18)); // NOI18N
        content.setRows(5);
        jScrollPane1.setViewportView(content);

        background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 440, 90));

        time_sent.setFont(new java.awt.Font("Arimo", 0, 18)); // NOI18N
        time_sent.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        time_sent.setText("jLabel1");
        background.add(time_sent, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 400, -1));

        add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 470, 200));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JTextArea content;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel status_view;
    private javax.swing.JLabel time_sent;
    private javax.swing.JLabel user_name;
    // End of variables declaration//GEN-END:variables
}
