/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DTO.GroupChatDTO;
import DTO.UserDTO;

/**
 *
 * @author mthuan
 */
public class User_item extends javax.swing.JPanel {
    UserDTO user;
    /**
     * Creates new form Group_Item
     */
    public User_item(UserDTO u) {
        this.user = u;
        initComponents();
        display();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        group_name = new javax.swing.JLabel();
        group_status = new javax.swing.JLabel();
        join_chat = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        block_user = new javax.swing.JButton();
        lastMess = new javax.swing.JLabel();

        background.setBackground(new java.awt.Color(254, 254, 254));
        background.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        group_name.setFont(new java.awt.Font("Arimo", 1, 20)); // NOI18N
        group_name.setText("ten nhom chat");
        background.add(group_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 450, 20));

        group_status.setFont(new java.awt.Font("Arimo", 0, 18)); // NOI18N
        group_status.setText("trang thai");
        background.add(group_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 280, 20));

        join_chat.setFont(new java.awt.Font("Arimo", 1, 18)); // NOI18N
        join_chat.setText("Vào chat");
        background.add(join_chat, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 140, 50));

        jPanel1.setBackground(new java.awt.Color(87, 87, 87));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 300, 10));

        block_user.setFont(new java.awt.Font("Arimo", 1, 18)); // NOI18N
        block_user.setText("Chặn");
        background.add(block_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 140, 50));
        background.add(lastMess, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 310, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton block_user;
    private javax.swing.JLabel group_name;
    private javax.swing.JLabel group_status;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton join_chat;
    private javax.swing.JLabel lastMess;
    // End of variables declaration//GEN-END:variables

    private void display() {
        group_name.setText(user.getName());
        group_status.setText(user.isIsBlock() ? "Bạn đã bị chặn chat":"");
        lastMess.setText(user.getLastMessage());
    }
    
    @Override
    public String toString(){
        return group_name.getText() +group_status.getText() + lastMess.getText();
    }
}
