/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DTO.GroupChatDTO;
import DTO.UserDTO;
import Func.Hyrid_Encryption;
import Network.Config;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.net.Socket;
import java.security.NoSuchAlgorithmException;
import java.security.PublicKey;
import java.util.Base64;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.KeyGenerator;
import javax.crypto.SecretKey;
import javax.swing.JOptionPane;

/**
 *
 * @author mthuan
 */
public class User_item_block extends javax.swing.JPanel {
    UserDTO user;
    UserDTO userBlock;
    String randomKey;
    PublicKey pKeyServer;
    String PUBLIC_KEY_SERVER = "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCbPndbAp25koChNaXO9XfZHLBEVKWedG5c2Inio657AePBaYzYISc2ucXwHDzn+xJsFbthGzyt+CYsnVdrtwpVB3Pv7TpWnj2W2l0yG5vrOjsUERVBaC+6Mk1+RNXRimqxCJDtJTtXeB9/bZGXBe4WcPXUhwIB563JPyAGTyeVnwIDAQAB";
    
    /**
     * Creates new form Group_Item
     */
    public User_item_block(UserDTO u,UserDTO uBlock) {
        this.user = u;
        this.userBlock = uBlock;
        initComponents();
        display();
        initSocket();
    }
    
    private void initSocket() {
        try {
            //Tao random key
            KeyGenerator keyGen = KeyGenerator.getInstance("AES");
            keyGen.init(256); // for example
            SecretKey secretKey = keyGen.generateKey();
            randomKey = Base64.getEncoder().encodeToString(secretKey.getEncoded());
            pKeyServer = Hyrid_Encryption.getPublicKeyRSA(PUBLIC_KEY_SERVER);            

        } catch (NoSuchAlgorithmException ex) {
            System.out.println(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        user_name = new javax.swing.JLabel();
        unblock_user = new javax.swing.JButton();

        background.setBackground(new java.awt.Color(254, 254, 254));
        background.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user_name.setFont(new java.awt.Font("Arimo", 1, 20)); // NOI18N
        user_name.setText("ten nhom chat");
        background.add(user_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, 20));

        unblock_user.setBackground(new java.awt.Color(255, 0, 0));
        unblock_user.setFont(new java.awt.Font("Arimo", 1, 18)); // NOI18N
        unblock_user.setForeground(new java.awt.Color(254, 254, 254));
        unblock_user.setText("Bỏ Chặn");
        unblock_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unblock_userMouseClicked(evt);
            }
        });
        background.add(unblock_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 140, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void unblock_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unblock_userMouseClicked
        // TODO add your handling code here:
        int choose = JOptionPane.showConfirmDialog(null, "Bạn có muốn unblock user này không ?","Cảnh báo",JOptionPane.YES_NO_OPTION);
        if(choose != 0){
            return;
        }
        
        new Thread(new UnBlockUser(user,userBlock,pKeyServer,randomKey)).start();
    }//GEN-LAST:event_unblock_userMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton unblock_user;
    private javax.swing.JLabel user_name;
    // End of variables declaration//GEN-END:variables

    private void display() {
        user_name.setText(userBlock.getName());
    }
    
    @Override
    public String toString(){
        return user_name.getText();
    }
    
    private class UnBlockUser implements Runnable {
        UserDTO user;
        UserDTO userBlock;
        PublicKey pKeyServer;
        String randomKey;
        Socket socket;

        public UnBlockUser(UserDTO user, UserDTO userBlock, PublicKey pKeyServer, String randomKey) {
            this.user = user;
            this.userBlock = userBlock;
            this.pKeyServer = pKeyServer;
            this.randomKey = randomKey;
        }

        @Override
        public void run() {
            try {
                socket = new Socket(Config.HOST,Config.PORT);
                BufferedWriter output = new BufferedWriter(new OutputStreamWriter(socket.getOutputStream()));

                
                    HashMap<String, String> maps = new HashMap<>();
                    int []str = {user.getId(),userBlock.getId()};
                    //Khoi tao data          
                    maps.put("command", "UNBLOCK_USER");
                    maps.put("data", new Gson().toJson(str));
                    //Ma hoa du lieu
                    String data = new Gson().toJson(maps);
                    data = Hyrid_Encryption.encryptAES(data, randomKey);
                    //Ma hoa randomkey
                    String encryptRandomKey = Hyrid_Encryption.encryptRSA(randomKey, pKeyServer);
                    //Tao du lieu gui den server                     
                    HashMap<String, String> sendServer = new HashMap<>();
                    sendServer.put("key", encryptRandomKey);
                    sendServer.put("value", data);
                    String strSend = new Gson().toJson(sendServer);

                    output.write(strSend);
                    output.newLine();
                    output.flush();
                    
                    //Read result
                    // Doc du lieu
                    BufferedReader input = new BufferedReader(new InputStreamReader(socket.getInputStream()));
                    String inputStr = input.readLine();

                    //Giai ma du lieu
                    inputStr = Hyrid_Encryption.decryptAES(inputStr, randomKey);
                    if (inputStr == null) {
                        return;
                    }
                    //ep kieu thanh hashmap
                    maps = new Gson().fromJson(inputStr, new TypeToken<HashMap<String, String>>() {
                    }.getType());
                    
                    JOptionPane.showMessageDialog(null, maps.get("result"));
                

            } catch (Exception ex) {
                System.out.println(ex.getMessage());
            }
        }        
    }
}
