/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Room;

import DTO.Room;
import DTO.User;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.awt.Container;
import java.awt.GridLayout;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import static sun.misc.GThreadHelper.lock;

/**
 *
 * @author mthuan
 */
public class Chat_Room extends javax.swing.JFrame {

    DataInputStream input = null;
    DataOutputStream output = null;
    Socket s = null;
    User user = null;

    /**
     * Creates new form Chat_Room
     */
    public Chat_Room() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            s = new Socket("127.0.0.1", 8888);

            loadRoomChat loadRoom = new loadRoomChat(s, listRoomContainer);
            loadRoom.run();

        } catch (IOException ex) {
            Logger.getLogger(Chat_Room.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    public Chat_Room(User user) {
        initComponents();
        this.user = user;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        ListRoom = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        listRoomContainer = new javax.swing.JScrollPane();
        refresh = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(202, 200, 200));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ListRoom.setBackground(new java.awt.Color(254, 254, 254));
        ListRoom.setForeground(new java.awt.Color(1, 1, 1));

        jTextField1.setFont(new java.awt.Font("Arimo", 0, 24)); // NOI18N

        jButton1.setBackground(new java.awt.Color(0, 141, 255));
        jButton1.setFont(new java.awt.Font("Arimo", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(254, 254, 254));
        jButton1.setText("Tìm Kiếm");

        jLabel2.setFont(new java.awt.Font("Arimo", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 126, 255));
        jLabel2.setText("Danh Sách :");

        refresh.setText("Refresh");
        refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ListRoomLayout = new javax.swing.GroupLayout(ListRoom);
        ListRoom.setLayout(ListRoomLayout);
        ListRoomLayout.setHorizontalGroup(
            ListRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListRoomLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(ListRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listRoomContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ListRoomLayout.createSequentialGroup()
                        .addGroup(ListRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(34, 34, 34)
                        .addGroup(ListRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(refresh)
                            .addComponent(jButton1)))))
        );
        ListRoomLayout.setVerticalGroup(
            ListRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListRoomLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(ListRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(6, 6, 6)
                .addGroup(ListRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(refresh))
                .addGap(6, 6, 6)
                .addComponent(listRoomContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        background.add(ListRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 510));

        header.setBackground(new java.awt.Color(254, 254, 254));

        jLabel1.setBackground(new java.awt.Color(254, 254, 254));
        jLabel1.setFont(new java.awt.Font("BrushScript", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(9, 105, 254));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Messenger Pha Ke :)))");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 970, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        background.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 970, 50));

        jPanel1.setBackground(new java.awt.Color(231, 224, 224));

        jLabel3.setFont(new java.awt.Font("Arimo", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 126, 255));
        jLabel3.setText("Nội dung chat");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 403, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 538, Short.MAX_VALUE))
        );

        background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 640, 580));

        jPanel2.setBackground(new java.awt.Color(255, 123, 255));

        jLabel4.setFont(new java.awt.Font("Arimo", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 126, 255));
        jLabel4.setText("Thành Viên");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addContainerGap(272, Short.MAX_VALUE))
        );

        background.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 60, 280, 300));

        jPanel3.setBackground(new java.awt.Color(232, 157, 32));

        jLabel5.setFont(new java.awt.Font("Arimo", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 126, 255));
        jLabel5.setText("Chức năng ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 146, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 92, Short.MAX_VALUE))
        );

        background.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 520, 280, 120));

        jPanel4.setBackground(new java.awt.Color(2, 163, 24));

        jLabel6.setFont(new java.awt.Font("Arimo", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 126, 255));
        jLabel6.setText("Lưu trữ file");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 150, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 132, Short.MAX_VALUE))
        );

        background.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 360, 280, 160));

        jPanel5.setBackground(new java.awt.Color(158, 168, 1));

        jLabel7.setFont(new java.awt.Font("Arimo", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 126, 255));
        jLabel7.setText("Chức năng ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(0, 396, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(0, 92, Short.MAX_VALUE))
        );

        background.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 516, 530, 120));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMouseClicked
        // TODO add your handling code here:
        listRoomContainer.removeAll();
        listRoomContainer.revalidate();
        listRoomContainer.repaint();
        loadRoomChat load = new loadRoomChat(s, listRoomContainer);
        load.run();
        
    }//GEN-LAST:event_refreshMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chat_Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chat_Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chat_Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chat_Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chat_Room().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ListRoom;
    private javax.swing.JPanel background;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JScrollPane listRoomContainer;
    private javax.swing.JButton refresh;
    // End of variables declaration//GEN-END:variables
}

class loadRoomChat implements Runnable {

    Socket s;
    JScrollPane scroll = null;
    final int WIDTH_ITEM = 600;
    final int HEIGHT_ITEM = 50;

    public loadRoomChat(Socket s, JScrollPane scroll) {
        this.scroll = scroll;
        this.s = s;
    }

    @Override
    public synchronized void run() {
        
        try {
            System.out.println("Load giao dien");
            
            DataInputStream input = new DataInputStream(s.getInputStream());
            DataOutputStream output = new DataOutputStream(s.getOutputStream());

            HashMap<String, String> maps = new HashMap<>();
            maps.put("command", "GET_ALL_ROOM");
            output.writeUTF(new Gson().toJson(maps));

            String line = input.readUTF();
            maps = new Gson().fromJson(line, new TypeToken<HashMap<String, String>>() {
            }.getType());

            if (maps.get("result").compareTo("SUCCESS") == 0) {
                List<Room> listRoom = new Gson().fromJson(maps.get("data"), new TypeToken<List<Room>>() {
                }.getType());

                Container container = new Container();
                for (Room r : listRoom) {
                    JPanel roomItem = new Room_Item(r);
                    roomItem.setSize(WIDTH_ITEM, HEIGHT_ITEM);
                    roomItem.setVisible(true);
                    container.add(roomItem);
                }

                for (Room r : listRoom) {
                    JPanel roomItem = new Room_Item(r);
                    roomItem.setSize(WIDTH_ITEM, HEIGHT_ITEM);
                    roomItem.setVisible(true);
                    container.add(roomItem);
                }

                container.setLayout(new GridLayout(listRoom.size() * 2, 1));
                scroll.getViewport().setView(container);

            } else {
                JOptionPane.showMessageDialog(null, "Lỗi khi load rom chat !!!");
            }

        } catch (IOException e) {
            e.printStackTrace();
        }
    }

}
