/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Room;

import DTO.Room;
import DTO.User;

/**
 *
 * @author mthuan
 */
public class Room_Item extends javax.swing.JPanel {
    User user;
    Room room;
    /**
     * Creates new form Room_Item
     */
    public Room_Item() {
        initComponents();
    }

    public Room_Item(User user, Room room) {
        this.user = user;
        this.room = room;
        initComponents();
        
        initRoom();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        room_name = new javax.swing.JLabel();
        status_room = new javax.swing.JLabel();
        type_room = new javax.swing.JLabel();
        join_room = new javax.swing.JButton();

        setBackground(new java.awt.Color(254, 160, 160));

        room_name.setFont(new java.awt.Font("Arimo", 0, 24)); // NOI18N
        room_name.setText("Ten Phong");

        status_room.setFont(new java.awt.Font("Arimo", 0, 24)); // NOI18N
        status_room.setText("Trang Thai");

        type_room.setFont(new java.awt.Font("Arimo", 0, 24)); // NOI18N
        type_room.setText("Loai Phong");

        join_room.setFont(new java.awt.Font("Arimo", 1, 24)); // NOI18N
        join_room.setText("Tham Gia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(room_name, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(status_room, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(type_room, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(join_room)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(room_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(type_room)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(status_room)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(join_room)
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton join_room;
    private javax.swing.JLabel room_name;
    private javax.swing.JLabel status_room;
    private javax.swing.JLabel type_room;
    // End of variables declaration//GEN-END:variables

    private void initRoom() {
        room_name.setText(room.getName());
       type_room.setText("Loại Phòng : " + (room.isGroup_chat() ? "Chat nhóm " : "Chat 1-1"));
       
       
    }
}
