/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Room;

import DTO.Room;

/**
 *
 * @author mthuan
 */
public class Room_Item extends javax.swing.JPanel {

    /**
     * Creates new form Room_Item
     */
    public Room_Item() {
        initComponents();
    }
    
    public Room_Item(Room room){
        initComponents();
        displayRoomInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nameRoom = new javax.swing.JLabel();
        idRoom = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        typeRoom1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(400, 100));

        jPanel1.setBackground(new java.awt.Color(1, 127, 238));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(254, 254, 254), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameRoom.setFont(new java.awt.Font("Arimo", 0, 24)); // NOI18N
        nameRoom.setForeground(new java.awt.Color(254, 254, 254));
        nameRoom.setText("Tên Nhóm");
        jPanel1.add(nameRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 347, -1));

        idRoom.setFont(new java.awt.Font("Arimo", 0, 24)); // NOI18N
        idRoom.setForeground(new java.awt.Color(254, 254, 254));
        idRoom.setText("ID Room :");
        jPanel1.add(idRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 240, -1));

        jButton1.setFont(new java.awt.Font("Arimo", 1, 24)); // NOI18N
        jButton1.setText("Tham Gia");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, 70));

        typeRoom1.setFont(new java.awt.Font("Arimo", 0, 24)); // NOI18N
        typeRoom1.setForeground(new java.awt.Color(254, 254, 254));
        typeRoom1.setText("Loại ");
        jPanel1.add(typeRoom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 230, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel idRoom;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nameRoom;
    private javax.swing.JLabel typeRoom1;
    // End of variables declaration//GEN-END:variables

    private void displayRoomInfo() {
        
    }
}
